### ISSUE TITLE
Is it working with VELUX solar window blinds?

### ISSUE THREAD

**Issue by KayGundhardt** [reefab/homeassistant-velux#3]
Hi everybody,
Salut Fabien,

it disassembled my VELUX **_solar window blinds_** **_MOTOR_** which has obviously more (5) than just 2 cables and it looks like this: 

![IMG_2126](https://user-images.githubusercontent.com/69385168/182774146-c48fc1b1-0a5b-4231-8bc5-54b55da91d5c.jpg)
![IMG_2127](https://user-images.githubusercontent.com/69385168/182774212-ebe995e5-98b0-47ec-92cc-cc3d308c5f04.jpg)

... to be connected to the SONOFF 4CH Pro (R3). 

As you can see I tried to connect to the red and black cable. Does anyone has an idea if it could work although? Or am I totally wrong and it should be connected to the **_(RADIO) CONTROLLER_** which looks like this:

(bottom-view)
![IMG_2129](https://user-images.githubusercontent.com/69385168/182774274-c02b18be-4514-423e-8449-b534da7ef3ff.jpg)

(top-view)
![IMG_2128](https://user-images.githubusercontent.com/69385168/182774232-330765cd-474e-4f69-87dc-997ffd4ada3a.jpg)

Any help would be really appreciated!

Kay

**Comment by manu-t** [comment]
Hi, 
I guess it's the same as the non-solar version: once you paired it with the remote control, you're screwed. Because the power supply will not source current to the motor anymore.
3 of the 5 wires are very likely here to interface an encoder (but which one is which?, I don't know).
I tryed to replace the motor controller board by a relay (a Z-Wave one) and the power supply by an off-the-shelf 24V-2A, but it failed as is: the motor inrush current is too high for my 2 amp power supply. I guess that the motor controller board has some sort of soft start to deal with the inrush current. I stopped expermimenting here because lack of time.
I think it would be even harder for the solar version to replace the controller board as the controller probably takes also care of the battery charging with the solar panel (maybe there is some sort of BMS implemented).

**Comment by KayGundhardt** [comment]
Okay, I See - thank you for your reply!

What about inserting an old (2-wired) motor: does anyone know if it fits the solar-motor-case?

**Comment by manu-t** [comment]
It's an old controller board (before 2014) that you need. I don't if it will fit though...

**Comment by KayGundhardt** [comment]
Like this?

https://m.ebay-kleinanzeigen.de/s-anzeige/3-x-velux-motor-type-40as10b-fuer-velux-rolladen-rohrmotor-24v/2154684044-87-18154

**Comment by KayGundhardt** [comment]
Just to get this clear: following the original repository I have to connect DIRECTLY to the two motor cables of an velux SML motor, right? NOT to any of the wires of its controller....

**Comment by manu-t** [comment]
if you haven't pair it with a remote control only (new motor). If it has been paired, applying +/-24V won't make the motor turn

**Comment by reefab** [comment]
Sorry, I can't really help you with the solar blinds as I don't have one  

If you intend to replace them with a SML, I can't confirm if the wires used in the guide are the ones coming directly out of the motor. I'm not sure if there is a driver board between the motor as my blinds came in as a complete unit with the wires coming out.

If the motor is indeed 24V, it's worth a try anyway.  It shouldn't hurt. 

Just using a 24V power supply, connect it to the motor for a while, don't be surprised if it doesn't spin right away. Reverse the polarity to make sure it is spinning the other direction and grab it at one point to make sure it can sense getting stuck.

If you source it from a place with a decent return policy, it should be a quick and risk free test.

**Comment by reefab** [comment]
If it works and you've successfully replaced the motor of your blinds make sure to let me know and I'll amend the guide.

I'm no veluxologist and I appreciate any help I can get.

**Comment by KayGundhardt** [comment]
OK, thank you very much for your reply! Just to get this clear: so your entire unit had only two 24v cables?

**Comment by KayGundhardt** [comment]
Hello there! 

It works: at least somehow…

The only thing is, that the motor turns only in one direction, no matter if it push the up or down Buttons in HA: I controlled the wiring twice now - maybe something with the flashed sonoff? Could some please help me check if the sonoff works correctly?

**Comment by KayGundhardt** [comment]
Here’s the velux.yaml I compiled:

```
esphome:
  name: Büro Dachfenster Rolladensteuerung
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 
  password: 

logger:
api:
ota:

binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - cover.open: velux_1
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - cover.close: velux_1
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - cover.open: velux_2
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - cover.close: velux_2

  - platform: status
    name: "Büro Dachfenster Rolladen Status"

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  - platform: monochromatic
    name: "Blue LED"
    output: blue_led

switch:
  - platform: gpio
    pin: GPIO12
    id: "relay_1"
  - platform: gpio
    pin: GPIO5
    id: "relay_2"
  - platform: gpio
    pin: GPIO4
    id: "relay_3"
  - platform: gpio
    pin: GPIO15
    id: "relay_4"

cover:
  - platform: template
    id: velux_1
    name: "Büro Dachfenster Rolladen"
    open_action:
      - switch.turn_off: relay_2
      - switch.turn_on: relay_1
    close_action:
      - switch.turn_off: relay_1
      - switch.turn_on: relay_2
    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
    optimistic: true
  - platform: template
    id: velux_2
    name: "Ungenutze Rolladensteuerung"
    open_action:
      - switch.turn_off: relay_4
      - switch.turn_on: relay_3
    close_action:
      - switch.turn_off: relay_3
      - switch.turn_on: relay_4
    stop_action:
      - switch.turn_off: relay_3
      - switch.turn_off: relay_4
    optimistic: true
```
