### ISSUE TITLE
New Layout ESPhome

### ISSUE THREAD

**Issue by jwvdhelm** [reefab/homeassistant-velux#8]
Hi,
first of all many thanks for sharing this, works great!

No big deal but with the new ESPhome the Velux.yaml needs a different layout, i had to change it in to this:
```
esphome:
  name: sonoff4chpro

esp8266:
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:
  - platform: esphome
```
